// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/listar-paineis.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Chave p\xFAblica do Supabase n\xE3o encontrada no ambiente");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("Sess\xE3o autenticada obrigat\xF3ria");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/helpers.ts
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) throw new Error("N\xE3o autenticado");
  const userId = ctx.getUserId();
  if (!userId) throw new Error("N\xE3o foi poss\xEDvel identificar o usu\xE1rio");
  return userId;
}
function ok(payload) {
  const text = typeof payload === "string" ? payload : JSON.stringify(payload, null, 2);
  return { content: [{ type: "text", text }] };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function onlyDigits(value) {
  if (!value) return null;
  const digits = value.replace(/\D/g, "");
  return digits.length ? digits : null;
}
var CROSS_PANEL_ID = "painel_msj9fyji";

// src/lib/mcp/tools/listar-paineis.ts
var listar_paineis_default = defineTool({
  name: "listar_paineis",
  title: "Listar pain\xE9is e etapas",
  description: "Lista os pain\xE9is do CRM (comercial, onboarding, Onb Clientes Cross etc.) e as etapas de cada um.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const [panels, stages] = await Promise.all([
      supabase.from("pipeline_panels").select("id, name, sort_order").order("sort_order"),
      supabase.from("pipeline_stages_config").select("panel_key, value, label, sort_order").order("sort_order")
    ]);
    if (panels.error) return fail(panels.error.message);
    if (stages.error) return fail(stages.error.message);
    const result = (panels.data ?? []).map((p) => ({
      panel_id: p.id,
      nome: p.name,
      etapas: (stages.data ?? []).filter((s) => s.panel_key === p.id).map((s) => ({ stage_id: s.value, label: s.label }))
    }));
    return ok(result);
  }
});

// src/lib/mcp/tools/listar-leads.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var listar_leads_default = defineTool2({
  name: "listar_leads",
  title: "Listar leads",
  description: "Busca cards de lead do CRM por texto (nome fantasia, raz\xE3o social, CNPJ, respons\xE1vel, e-mail), painel e etapa.",
  inputSchema: {
    busca: z.string().optional().describe("Texto livre para buscar por nome, CNPJ, respons\xE1vel ou e-mail."),
    panel_id: z.string().optional().describe("ID do painel, ex.: comercial."),
    stage_id: z.string().optional().describe("Etapa do funil, ex.: novo_lead."),
    limite: z.number().int().optional().describe("Quantidade de registros (padr\xE3o 25, m\xE1ximo 100)."),
    offset: z.number().int().optional().describe("Deslocamento para pagina\xE7\xE3o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, panel_id, stage_id, limite, offset }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limite ?? 25, 1), 100);
    const from = Math.max(offset ?? 0, 0);
    let query = supabase.from("leads").select(
      "id, nome_fantasia, razao_social, cnpj, cidade, nome_responsavel, telefone_responsavel, email_responsavel, status_lead, panel_id, consultor, data_cadastro"
    ).order("data_cadastro", { ascending: false }).range(from, from + take - 1);
    if (panel_id) query = query.eq("panel_id", panel_id);
    if (stage_id) query = query.eq("status_lead", stage_id);
    if (busca?.trim()) {
      const term = busca.trim().replace(/[%,()]/g, " ");
      query = query.or(
        [
          `nome_fantasia.ilike.%${term}%`,
          `razao_social.ilike.%${term}%`,
          `cnpj.ilike.%${term}%`,
          `nome_responsavel.ilike.%${term}%`,
          `email_responsavel.ilike.%${term}%`
        ].join(",")
      );
    }
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ total_retornado: data?.length ?? 0, leads: data ?? [] });
  }
});

// src/lib/mcp/tools/obter-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var obter_lead_default = defineTool3({
  name: "obter_lead",
  title: "Detalhe do lead",
  description: "Retorna o card completo de um lead, com coment\xE1rios e tarefas.",
  inputSchema: { lead_id: z2.string().describe("UUID do lead.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: lead, error } = await supabase.from("leads").select("*").eq("id", lead_id).maybeSingle();
    if (error) return fail(error.message);
    if (!lead) return fail("Lead n\xE3o encontrado ou sem permiss\xE3o de acesso.");
    const [comentarios, tarefas] = await Promise.all([
      supabase.from("lead_comments").select("id, etapa, usuario, comentario, data_comentario").eq("lead_id", lead_id).order("data_comentario", { ascending: false }).limit(50),
      supabase.from("lead_tasks").select("id, titulo, status, due_at, due_date, assigned_to, completed_at").eq("lead_id", lead_id).order("created_at", { ascending: false }).limit(50)
    ]);
    return ok({ lead, comentarios: comentarios.data ?? [], tarefas: tarefas.data ?? [] });
  }
});

// src/lib/mcp/tools/listar-embaixadores.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var listar_embaixadores_default = defineTool4({
  name: "listar_embaixadores",
  title: "Listar Embaixadores Monnera",
  description: "Lista os Embaixadores Monnera ativos e aprovados, com id e c\xF3digo, para vincular a novos leads.",
  inputSchema: {
    busca: z3.string().optional().describe("Filtra por nome, e-mail ou c\xF3digo do embaixador."),
    limite: z3.number().int().optional().describe("Quantidade de registros (padr\xE3o 50, m\xE1ximo 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, limite }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limite ?? 50, 1), 200);
    let query = supabase.from("parceiros_comerciais").select("id, codigo_parceiro, nome, email, slug_consultor, ativo, aprovado").eq("ativo", true).eq("aprovado", true).order("nome").limit(take);
    if (busca?.trim()) {
      const term = busca.trim().replace(/[%,()]/g, " ");
      query = query.or(
        [`nome.ilike.%${term}%`, `email.ilike.%${term}%`, `codigo_parceiro.ilike.%${term}%`].join(",")
      );
    }
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok(data ?? []);
  }
});

// src/lib/mcp/tools/listar-responsaveis.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var listar_responsaveis_default = defineTool5({
  name: "listar_responsaveis",
  title: "Listar respons\xE1veis dispon\xEDveis",
  description: "Lista os usu\xE1rios que podem ser respons\xE1veis por um card (para preencher responsible_user_id).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("get_available_responsible_users");
    if (error) return fail(error.message);
    return ok(data ?? []);
  }
});

// src/lib/mcp/tools/criar-lead.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var criar_lead_default = defineTool6({
  name: "criar_lead",
  title: "Criar card de lead",
  description: "Cria um novo card de lead no funil comercial. Exige o embaixador (parceiro_id, obtido em listar_embaixadores).",
  inputSchema: {
    nome_fantasia: z4.string().describe("Nome fantasia da empresa."),
    nome_responsavel: z4.string().describe("Nome do contato respons\xE1vel."),
    telefone_responsavel: z4.string().describe("Telefone do respons\xE1vel."),
    parceiro_id: z4.string().describe("UUID do Embaixador Monnera respons\xE1vel pela indica\xE7\xE3o."),
    email_responsavel: z4.string().optional(),
    razao_social: z4.string().optional(),
    cnpj: z4.string().optional(),
    cidade: z4.string().optional(),
    quantidade_lojas: z4.number().int().optional(),
    erp_utilizado: z4.string().optional(),
    descricao_necessidade: z4.string().optional(),
    panel_id: z4.string().optional().describe("Painel do card (padr\xE3o: comercial)."),
    stage_id: z4.string().optional().describe("Etapa inicial (padr\xE3o: novo_lead)."),
    origem: z4.string().optional().describe("Origem do lead (padr\xE3o: agente_codex)."),
    responsible_user_id: z4.string().optional().describe("Usu\xE1rio respons\xE1vel pelo card.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const stage = input.stage_id?.trim() || "novo_lead";
    const payload = {
      nome_fantasia: input.nome_fantasia.trim(),
      razao_social: input.razao_social?.trim() || null,
      cnpj: onlyDigits(input.cnpj),
      cidade: input.cidade?.trim() || null,
      quantidade_lojas: input.quantidade_lojas ?? null,
      nome_responsavel: input.nome_responsavel.trim(),
      telefone_responsavel: input.telefone_responsavel.trim(),
      email_responsavel: input.email_responsavel?.trim().toLowerCase() || null,
      erp_utilizado: input.erp_utilizado?.trim() || null,
      descricao_necessidade: input.descricao_necessidade?.trim() || null,
      parceiro_id: input.parceiro_id,
      panel_id: input.panel_id?.trim() || "comercial",
      status: stage,
      status_lead: stage,
      origem: input.origem?.trim() || "agente_codex",
      ...input.responsible_user_id ? { responsible_user_id: input.responsible_user_id } : {}
    };
    const { data, error } = await supabase.from("leads").insert(payload).select("id, nome_fantasia, status_lead, panel_id").single();
    if (error) {
      if (error.message.includes("duplicate key")) return fail("J\xE1 existe um lead com esses dados (CNPJ ou e-mail duplicado).");
      return fail(error.message);
    }
    return ok({ criado: true, lead: data });
  }
});

// src/lib/mcp/tools/atualizar-lead.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var atualizar_lead_default = defineTool7({
  name: "atualizar_lead",
  title: "Atualizar card de lead",
  description: "Atualiza campos cadastrais de um card de lead existente. S\xF3 envie os campos que devem mudar.",
  inputSchema: {
    lead_id: z5.string().describe("UUID do lead."),
    nome_fantasia: z5.string().optional(),
    razao_social: z5.string().optional(),
    cnpj: z5.string().optional(),
    cidade: z5.string().optional(),
    quantidade_lojas: z5.number().int().optional(),
    nome_responsavel: z5.string().optional(),
    telefone_responsavel: z5.string().optional(),
    email_responsavel: z5.string().optional(),
    erp_utilizado: z5.string().optional(),
    descricao_necessidade: z5.string().optional(),
    valor_mensalidade: z5.number().optional(),
    valor_campanhas: z5.number().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, cnpj, email_responsavel, ...rest }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const updates = {};
    for (const [key, value] of Object.entries(rest)) {
      if (value !== void 0) updates[key] = typeof value === "string" ? value.trim() : value;
    }
    if (cnpj !== void 0) updates.cnpj = onlyDigits(cnpj);
    if (email_responsavel !== void 0) updates.email_responsavel = email_responsavel.trim().toLowerCase() || null;
    if (Object.keys(updates).length === 0) return fail("Nenhum campo informado para atualiza\xE7\xE3o.");
    const { data, error } = await supabase.from("leads").update(updates).eq("id", lead_id).select("id").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Lead n\xE3o encontrado ou sem permiss\xE3o para editar.");
    return ok({ atualizado: true, lead_id, campos: Object.keys(updates) });
  }
});

// src/lib/mcp/tools/mover-lead-etapa.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z6 } from "npm:zod@^3.25.76";
var mover_lead_etapa_default = defineTool8({
  name: "mover_lead_etapa",
  title: "Mover lead de etapa",
  description: "Move um card de lead para outra etapa do funil. Ao mover para lead_perdido, o motivo da perda \xE9 obrigat\xF3rio.",
  inputSchema: {
    lead_id: z6.string().describe("UUID do lead."),
    stage_id: z6.string().describe("Etapa de destino, ex.: reuniao_agendada."),
    motivo_perda: z6.string().optional().describe("Obrigat\xF3rio quando a etapa for lead_perdido.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, stage_id, motivo_perda }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const stage = stage_id.trim();
    if (stage === "lead_perdido" && !motivo_perda?.trim()) {
      return fail("Informe o motivo da perda para mover o card para lead_perdido.");
    }
    const { data: lead, error: leadError } = await supabase.from("leads").select("id, panel_id").eq("id", lead_id).maybeSingle();
    if (leadError) return fail(leadError.message);
    if (!lead) return fail("Lead n\xE3o encontrado ou sem permiss\xE3o de acesso.");
    const { data: stageRow } = await supabase.from("pipeline_stages_config").select("value").eq("panel_key", lead.panel_id).eq("value", stage).maybeSingle();
    if (!stageRow) return fail(`Etapa "${stage}" n\xE3o existe no painel ${lead.panel_id}.`);
    const updates = { status: stage, status_lead: stage };
    if (motivo_perda?.trim()) updates.motivo_perda = motivo_perda.trim();
    const { error } = await supabase.from("leads").update(updates).eq("id", lead_id);
    if (error) return fail(error.message);
    return ok({ movido: true, lead_id, stage_id: stage });
  }
});

// src/lib/mcp/tools/adicionar-comentario.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z7 } from "npm:zod@^3.25.76";
var adicionar_comentario_default = defineTool9({
  name: "adicionar_comentario",
  title: "Adicionar coment\xE1rio no card",
  description: "Registra um coment\xE1rio no card de lead, na etapa atual do card.",
  inputSchema: {
    lead_id: z7.string().describe("UUID do lead."),
    comentario: z7.string().describe("Texto do coment\xE1rio.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, comentario }, ctx) => {
    const userId = requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const texto = comentario.trim();
    if (!texto) return fail("O coment\xE1rio n\xE3o pode ficar vazio.");
    const { data: lead, error: leadError } = await supabase.from("leads").select("id, status_lead").eq("id", lead_id).maybeSingle();
    if (leadError) return fail(leadError.message);
    if (!lead) return fail("Lead n\xE3o encontrado ou sem permiss\xE3o de acesso.");
    const { data: profile } = await supabase.from("profiles").select("nome").eq("user_id", userId).maybeSingle();
    const { data, error } = await supabase.from("lead_comments").insert({
      lead_id,
      etapa: lead.status_lead,
      usuario: profile?.nome ?? ctx.getUserEmail() ?? "Agente",
      user_id: userId,
      comentario: texto
    }).select("id, data_comentario").single();
    if (error) return fail(error.message);
    return ok({ criado: true, comentario: data });
  }
});

// src/lib/mcp/tools/criar-tarefa.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z8 } from "npm:zod@^3.25.76";
var criar_tarefa_default = defineTool10({
  name: "criar_tarefa",
  title: "Criar tarefa no card",
  description: "Cria uma tarefa vinculada a um card de lead, com prazo e respons\xE1vel.",
  inputSchema: {
    lead_id: z8.string().describe("UUID do lead."),
    titulo: z8.string().describe("T\xEDtulo da tarefa."),
    due_at: z8.string().describe("Prazo em ISO 8601, ex.: 2026-08-20T14:00:00Z."),
    assigned_to: z8.string().optional().describe("UUID do usu\xE1rio respons\xE1vel (padr\xE3o: usu\xE1rio autenticado).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, titulo, due_at, assigned_to }, ctx) => {
    const userId = requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const prazo = new Date(due_at);
    if (Number.isNaN(prazo.getTime())) return fail("Prazo inv\xE1lido. Use o formato ISO 8601.");
    const { data, error } = await supabase.from("lead_tasks").insert({
      lead_id,
      titulo: titulo.trim(),
      due_at: prazo.toISOString(),
      due_date: prazo.toISOString().slice(0, 10),
      status: "pendente",
      assigned_to: assigned_to ?? userId,
      created_by: userId
    }).select("id, titulo, due_at, status").single();
    if (error) return fail(error.message);
    return ok({ criada: true, tarefa: data });
  }
});

// src/lib/mcp/tools/criar-cliente-cross.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z9 } from "npm:zod@^3.25.76";
var criar_cliente_cross_default = defineTool11({
  name: "criar_cliente_cross",
  title: "Criar cliente no painel Onb Clientes Cross",
  description: "Cria um card de cliente no painel Onb Clientes Cross com dados do parceiro, focal, contratante Monnera e vendedor. CNPJ \xE9 \xFAnico neste painel.",
  inputSchema: {
    nome_parceiro: z9.string().describe("Nome do parceiro."),
    cnpj: z9.string().describe("CNPJ do parceiro (14 d\xEDgitos)."),
    focal_nome: z9.string().optional(),
    focal_telefone: z9.string().optional(),
    focal_email: z9.string().optional(),
    contratante_monnera: z9.string().optional(),
    vendedor_nome: z9.string().optional(),
    vendedor_telefone: z9.string().optional(),
    vendedor_email: z9.string().optional(),
    anotacoes: z9.string().optional().describe("Anota\xE7\xF5es livres, at\xE9 500 caracteres."),
    stage_id: z9.string().optional().describe("Etapa inicial (padr\xE3o: primeira etapa do painel)."),
    responsible_user_id: z9.string().optional().describe("Usu\xE1rio respons\xE1vel (padr\xE3o: usu\xE1rio autenticado).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const userId = requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const cnpj = onlyDigits(input.cnpj);
    if (!cnpj || cnpj.length !== 14) return fail("CNPJ inv\xE1lido: informe 14 d\xEDgitos.");
    if ((input.anotacoes?.length ?? 0) > 500) return fail("As anota\xE7\xF5es devem ter no m\xE1ximo 500 caracteres.");
    const { data: existente } = await supabase.from("representative_cards").select("id, full_name").eq("panel_id", CROSS_PANEL_ID).eq("cnpj", cnpj).maybeSingle();
    if (existente) return fail(`J\xE1 existe um cliente com este CNPJ: ${existente.full_name}.`);
    let stage = input.stage_id?.trim();
    if (!stage) {
      const { data: primeira } = await supabase.from("pipeline_stages_config").select("value").eq("panel_key", CROSS_PANEL_ID).order("sort_order").limit(1).maybeSingle();
      stage = primeira?.value;
    }
    if (!stage) return fail("N\xE3o foi poss\xEDvel determinar a etapa inicial do painel.");
    const { data, error } = await supabase.from("representative_cards").insert({
      panel_id: CROSS_PANEL_ID,
      stage_id: stage,
      full_name: input.nome_parceiro.trim(),
      cnpj,
      phone: input.focal_telefone?.trim() || "",
      email: input.focal_email?.trim().toLowerCase() || "",
      focal_name: input.focal_nome?.trim() || null,
      focal_phone: input.focal_telefone?.trim() || null,
      focal_email: input.focal_email?.trim().toLowerCase() || null,
      contratante_monnera: input.contratante_monnera?.trim() || null,
      vendor_name: input.vendedor_nome?.trim() || null,
      vendor_phone: input.vendedor_telefone?.trim() || null,
      vendor_email: input.vendedor_email?.trim().toLowerCase() || null,
      notes: input.anotacoes?.trim() || null,
      source: "agente_codex",
      responsible_user_id: input.responsible_user_id ?? userId,
      created_by_user_id: userId
    }).select("id, full_name, cnpj, stage_id").single();
    if (error) {
      if (error.message.includes("cnpj")) return fail("J\xE1 existe um cliente com este CNPJ.");
      return fail(error.message);
    }
    return ok({ criado: true, cliente: data });
  }
});

// src/lib/mcp/tools/atualizar-cliente-cross.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z10 } from "npm:zod@^3.25.76";
var atualizar_cliente_cross_default = defineTool12({
  name: "atualizar_cliente_cross",
  title: "Atualizar cliente do painel Onb Clientes Cross",
  description: "Atualiza dados ou etapa de um card do painel Onb Clientes Cross. S\xF3 envie os campos que devem mudar.",
  inputSchema: {
    card_id: z10.string().describe("UUID do card do cliente."),
    nome_parceiro: z10.string().optional(),
    cnpj: z10.string().optional(),
    focal_nome: z10.string().optional(),
    focal_telefone: z10.string().optional(),
    focal_email: z10.string().optional(),
    contratante_monnera: z10.string().optional(),
    vendedor_nome: z10.string().optional(),
    vendedor_telefone: z10.string().optional(),
    vendedor_email: z10.string().optional(),
    anotacoes: z10.string().optional().describe("Anota\xE7\xF5es livres, at\xE9 500 caracteres."),
    stage_id: z10.string().optional().describe("Nova etapa do card.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    if ((input.anotacoes?.length ?? 0) > 500) return fail("As anota\xE7\xF5es devem ter no m\xE1ximo 500 caracteres.");
    const updates = {};
    if (input.nome_parceiro !== void 0) updates.full_name = input.nome_parceiro.trim();
    if (input.focal_nome !== void 0) updates.focal_name = input.focal_nome.trim() || null;
    if (input.focal_telefone !== void 0) {
      updates.focal_phone = input.focal_telefone.trim() || null;
      updates.phone = input.focal_telefone.trim() || "";
    }
    if (input.focal_email !== void 0) {
      updates.focal_email = input.focal_email.trim().toLowerCase() || null;
      updates.email = input.focal_email.trim().toLowerCase() || "";
    }
    if (input.contratante_monnera !== void 0) updates.contratante_monnera = input.contratante_monnera.trim() || null;
    if (input.vendedor_nome !== void 0) updates.vendor_name = input.vendedor_nome.trim() || null;
    if (input.vendedor_telefone !== void 0) updates.vendor_phone = input.vendedor_telefone.trim() || null;
    if (input.vendedor_email !== void 0) updates.vendor_email = input.vendedor_email.trim().toLowerCase() || null;
    if (input.anotacoes !== void 0) updates.notes = input.anotacoes.trim() || null;
    if (input.stage_id !== void 0) updates.stage_id = input.stage_id.trim();
    if (input.cnpj !== void 0) {
      const cnpj = onlyDigits(input.cnpj);
      if (!cnpj || cnpj.length !== 14) return fail("CNPJ inv\xE1lido: informe 14 d\xEDgitos.");
      const { data: existente } = await supabase.from("representative_cards").select("id").eq("panel_id", CROSS_PANEL_ID).eq("cnpj", cnpj).neq("id", input.card_id).maybeSingle();
      if (existente) return fail("J\xE1 existe outro cliente com este CNPJ.");
      updates.cnpj = cnpj;
    }
    if (Object.keys(updates).length === 0) return fail("Nenhum campo informado para atualiza\xE7\xE3o.");
    const { data, error } = await supabase.from("representative_cards").update(updates).eq("id", input.card_id).eq("panel_id", CROSS_PANEL_ID).select("id, full_name, cnpj, stage_id").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o para editar.");
    return ok({ atualizado: true, cliente: data });
  }
});

// src/lib/mcp/tools/mover-cliente-cross-etapa.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z11 } from "npm:zod@^3.25.76";
var normalize = (value) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim().toLowerCase();
var mover_cliente_cross_etapa_default = defineTool13({
  name: "mover_cliente_cross_etapa",
  title: "Mover cliente do painel Onb Clientes Cross de etapa",
  description: 'Move um card do painel Onb Clientes Cross para outra etapa. Aceita o stage_id ou o nome da etapa (ex.: "Aguardando Informa\xE7\xF5es").',
  inputSchema: {
    card_id: z11.string().describe("UUID do card do cliente."),
    etapa: z11.string().describe("Etapa de destino: stage_id (ex.: etapa_painel_msj9fyji_1786676252012) ou o r\xF3tulo, ex.: Aguardando Informa\xE7\xF5es.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ card_id, etapa }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: stages, error: stagesError } = await supabase.from("pipeline_stages_config").select("value, label, sort_order").eq("panel_key", CROSS_PANEL_ID).order("sort_order");
    if (stagesError) return fail(stagesError.message);
    const alvo = normalize(etapa);
    const stage = (stages ?? []).find(
      (s) => normalize(s.value) === alvo || normalize(s.label) === alvo
    );
    if (!stage) {
      const disponiveis = (stages ?? []).map((s) => `${s.label} (${s.value})`).join(", ");
      return fail(`Etapa "${etapa}" n\xE3o existe no painel Onb Clientes Cross. Dispon\xEDveis: ${disponiveis}`);
    }
    const { data, error } = await supabase.from("representative_cards").update({ stage_id: stage.value }).eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).select("id, full_name, cnpj, stage_id").maybeSingle();
    if (error) return fail(error.message);
    if (!data) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o para editar.");
    return ok({ movido: true, etapa: stage.label, cliente: data });
  }
});

// src/lib/mcp/tools/anexar-arquivo-cliente-cross.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z12 } from "npm:zod@^3.25.76";
var BUCKET = "representative-card-attachments";
var MAX_BYTES = 10 * 1024 * 1024;
var ALLOWED = ["pdf", "xls", "xlsx", "csv", "jpg", "jpeg", "png"];
var MIME = {
  pdf: "application/pdf",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  csv: "text/csv",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png"
};
function decodeBase64(input) {
  const clean = input.includes(",") && input.startsWith("data:") ? input.slice(input.indexOf(",") + 1) : input;
  const binary = atob(clean.replace(/\s+/g, ""));
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
var anexar_arquivo_cliente_cross_default = defineTool14({
  name: "anexar_arquivo_cliente_cross",
  title: "Anexar arquivo ao cliente do painel Onb Clientes Cross",
  description: "Envia um anexo (PDF, Excel/CSV ou imagem JPG/PNG, at\xE9 10 MB) para um card do painel Onb Clientes Cross. O conte\xFAdo do arquivo deve vir em base64. Arquivos id\xEAnticos j\xE1 anexados no card n\xE3o s\xE3o duplicados (verifica\xE7\xE3o por hash SHA-256).",
  inputSchema: {
    card_id: z12.string().describe("UUID do card do cliente."),
    file_name: z12.string().describe("Nome do arquivo com extens\xE3o, ex.: contrato.pdf."),
    conteudo_base64: z12.string().describe("Conte\xFAdo do arquivo codificado em base64 (aceita data URL).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ card_id, file_name, conteudo_base64 }, ctx) => {
    const userId = requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const ext = file_name.split(".").pop()?.toLowerCase() ?? "";
    if (!ALLOWED.includes(ext)) {
      return fail(`Formato n\xE3o permitido em "${file_name}". Use PDF, Excel (xls/xlsx/csv) ou imagem (jpg/png).`);
    }
    let bytes;
    try {
      bytes = decodeBase64(conteudo_base64);
    } catch {
      return fail("Conte\xFAdo base64 inv\xE1lido.");
    }
    if (!bytes.length) return fail("O arquivo est\xE1 vazio.");
    if (bytes.length > MAX_BYTES) return fail("O arquivo excede o limite de 10 MB.");
    const digest = await crypto.subtle.digest("SHA-256", bytes.slice().buffer);
    const hash = Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
    const { data: card, error: cardError } = await supabase.from("representative_cards").select("id").eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).maybeSingle();
    if (cardError) return fail(cardError.message);
    if (!card) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o de acesso.");
    const { data: existente } = await supabase.from("representative_card_attachments").select("id, file_name, size_bytes, created_at").eq("representative_card_id", card_id).eq("content_sha256", hash).maybeSingle();
    if (existente) {
      return ok({ anexado: false, duplicado: true, hash, anexo: existente });
    }
    const safeName = file_name.replace(/[^\w.\-]+/g, "_");
    const path = `${card_id}/${Date.now()}-${Math.random().toString(36).slice(2, 8)}-${safeName}`;
    const contentType = MIME[ext] ?? "application/octet-stream";
    const { error: uploadError } = await supabase.storage.from(BUCKET).upload(path, bytes, { contentType, upsert: false });
    if (uploadError) return fail(uploadError.message);
    const { data, error } = await supabase.from("representative_card_attachments").insert({
      representative_card_id: card_id,
      storage_path: path,
      file_name,
      mime_type: contentType,
      size_bytes: bytes.length,
      created_by: userId,
      content_sha256: hash
    }).select("id, file_name, size_bytes, created_at").single();
    if (error) {
      await supabase.storage.from(BUCKET).remove([path]);
      return fail(error.message);
    }
    return ok({ anexado: true, duplicado: false, hash, anexo: data });
  }
});

// src/lib/mcp/tools/listar-anexos-cliente-cross.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z13 } from "npm:zod@^3.25.76";
var BUCKET2 = "representative-card-attachments";
var listar_anexos_cliente_cross_default = defineTool15({
  name: "listar_anexos_cliente_cross",
  title: "Listar anexos do cliente Onb Clientes Cross",
  description: "Lista os anexos de um card do painel Onb Clientes Cross, com link tempor\xE1rio para download.",
  inputSchema: {
    card_id: z13.string().describe("UUID do card do cliente.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ card_id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: card } = await supabase.from("representative_cards").select("id").eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).maybeSingle();
    if (!card) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o de acesso.");
    const { data, error } = await supabase.from("representative_card_attachments").select("id, file_name, mime_type, size_bytes, storage_path, content_sha256, created_at").eq("representative_card_id", card_id).order("created_at", { ascending: false });
    if (error) return fail(error.message);
    const anexos = await Promise.all(
      (data ?? []).map(async (a) => {
        const { data: signed } = await supabase.storage.from(BUCKET2).createSignedUrl(a.storage_path, 60 * 10);
        return {
          id: a.id,
          file_name: a.file_name,
          mime_type: a.mime_type,
          size_bytes: a.size_bytes,
          created_at: a.created_at,
          hash_sha256: a.content_sha256,
          url: signed?.signedUrl ?? null
        };
      })
    );
    return ok({ total: anexos.length, anexos });
  }
});

// src/lib/mcp/tools/listar-clientes-cross.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z14 } from "npm:zod@^3.25.76";
var listar_clientes_cross_default = defineTool16({
  name: "listar_clientes_cross",
  title: "Listar clientes do painel Onb Clientes Cross",
  description: "Busca cards de cliente do painel Onb Clientes Cross por CNPJ, nome do parceiro, focal, contratante Monnera ou vendedor, com filtro opcional por etapa.",
  inputSchema: {
    busca: z14.string().optional().describe("Texto livre: CNPJ, nome do parceiro, focal, contratante ou vendedor."),
    etapa: z14.string().optional().describe("Filtra por stage_id da etapa."),
    limite: z14.number().int().optional().describe("Quantidade de registros (padr\xE3o 25, m\xE1ximo 100)."),
    offset: z14.number().int().optional().describe("Deslocamento para pagina\xE7\xE3o.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, etapa, limite, offset }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limite ?? 25, 1), 100);
    const skip = Math.max(offset ?? 0, 0);
    let query = supabase.from("representative_cards").select(
      "id, full_name, cnpj, stage_id, focal_name, focal_phone, focal_email, contratante_monnera, vendor_name, responsible_user_id, updated_at",
      { count: "exact" }
    ).eq("panel_id", CROSS_PANEL_ID).order("updated_at", { ascending: false }).range(skip, skip + take - 1);
    if (etapa) query = query.eq("stage_id", etapa);
    if (busca?.trim()) {
      const termo = busca.trim();
      const digits = onlyDigits(termo);
      const like = `%${termo}%`;
      const filtros = [
        `full_name.ilike.${like}`,
        `focal_name.ilike.${like}`,
        `focal_email.ilike.${like}`,
        `contratante_monnera.ilike.${like}`,
        `vendor_name.ilike.${like}`,
        `vendor_email.ilike.${like}`
      ];
      if (digits) filtros.push(`cnpj.ilike.%${digits}%`);
      query = query.or(filtros.join(","));
    }
    const { data, error, count } = await query;
    if (error) return fail(error.message);
    const { data: stages } = await supabase.from("pipeline_stages_config").select("value, label").eq("panel_key", CROSS_PANEL_ID);
    const labels = new Map((stages ?? []).map((s) => [s.value, s.label]));
    const clientes = (data ?? []).map((c) => ({
      ...c,
      etapa_label: labels.get(c.stage_id) ?? c.stage_id
    }));
    return ok({ total: count ?? clientes.length, retornados: clientes.length, clientes });
  }
});

// src/lib/mcp/tools/obter-cliente-cross.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z15 } from "npm:zod@^3.25.76";
var obter_cliente_cross_default = defineTool17({
  name: "obter_cliente_cross",
  title: "Detalhe do cliente Onb Clientes Cross",
  description: "Retorna o card completo de um cliente do painel Onb Clientes Cross, com etapa, coment\xE1rios, tarefas e anexos.",
  inputSchema: {
    card_id: z15.string().describe("UUID do card do cliente.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ card_id }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: card, error } = await supabase.from("representative_cards").select("*").eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).maybeSingle();
    if (error) return fail(error.message);
    if (!card) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o de acesso.");
    const [{ data: stage }, { data: comentarios }, { data: tarefas }, { data: anexos }] = await Promise.all([
      supabase.from("pipeline_stages_config").select("value, label, sort_order").eq("panel_key", CROSS_PANEL_ID).eq("value", card.stage_id).maybeSingle(),
      supabase.from("representative_card_comments").select("id, usuario, comentario, etapa, data_comentario").eq("representative_card_id", card_id).order("data_comentario", { ascending: false }).limit(50),
      supabase.from("representative_card_tasks").select("id, titulo, due_at, assigned_to, status, completed_at, completed_note").eq("representative_card_id", card_id).order("due_at", { ascending: true }),
      supabase.from("representative_card_attachments").select("id, file_name, mime_type, size_bytes, content_sha256, created_at").eq("representative_card_id", card_id).order("created_at", { ascending: false })
    ]);
    return ok({
      cliente: card,
      etapa: stage ? { stage_id: stage.value, label: stage.label, ordem: stage.sort_order } : { stage_id: card.stage_id },
      comentarios: comentarios ?? [],
      tarefas: tarefas ?? [],
      anexos: anexos ?? []
    });
  }
});

// src/lib/mcp/tools/listar-etapas-cross.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.26.2";
var listar_etapas_cross_default = defineTool18({
  name: "listar_etapas_cross",
  title: "Listar etapas do painel Onb Clientes Cross",
  description: 'Lista todas as etapas do painel Onb Clientes Cross (stage_id, r\xF3tulo e ordem), incluindo "Aguardando Informa\xE7\xF5es".',
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("pipeline_stages_config").select("value, label, sort_order").eq("panel_key", CROSS_PANEL_ID).order("sort_order");
    if (error) return fail(error.message);
    return ok({
      panel_id: CROSS_PANEL_ID,
      etapas: (data ?? []).map((s) => ({ stage_id: s.value, label: s.label, ordem: s.sort_order }))
    });
  }
});

// src/lib/mcp/tools/adicionar-comentario-cliente-cross.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z16 } from "npm:zod@^3.25.76";
var adicionar_comentario_cliente_cross_default = defineTool19({
  name: "adicionar_comentario_cliente_cross",
  title: "Adicionar coment\xE1rio no cliente Onb Clientes Cross",
  description: "Registra um coment\xE1rio no hist\xF3rico de um card do painel Onb Clientes Cross, na etapa atual do card.",
  inputSchema: {
    card_id: z16.string().describe("UUID do card do cliente."),
    comentario: z16.string().describe("Texto do coment\xE1rio.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ card_id, comentario }, ctx) => {
    const userId = requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const texto = comentario.trim();
    if (!texto) return fail("O coment\xE1rio n\xE3o pode ficar vazio.");
    const { data: card, error: cardError } = await supabase.from("representative_cards").select("id, stage_id").eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).maybeSingle();
    if (cardError) return fail(cardError.message);
    if (!card) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o de acesso.");
    const { data: profile } = await supabase.from("profiles").select("nome").eq("user_id", userId).maybeSingle();
    const { data, error } = await supabase.from("representative_card_comments").insert({
      representative_card_id: card_id,
      user_id: userId,
      etapa: card.stage_id,
      usuario: profile?.nome ?? ctx.getUserEmail() ?? "Agente",
      comentario: texto
    }).select("id, comentario, data_comentario").single();
    if (error) return fail(error.message);
    return ok({ criado: true, comentario: data });
  }
});

// src/lib/mcp/tools/listar-comentarios-cliente-cross.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z17 } from "npm:zod@^3.25.76";
var listar_comentarios_cliente_cross_default = defineTool20({
  name: "listar_comentarios_cliente_cross",
  title: "Listar hist\xF3rico do cliente Onb Clientes Cross",
  description: "Lista os coment\xE1rios (hist\xF3rico) de um card do painel Onb Clientes Cross, do mais recente para o mais antigo.",
  inputSchema: {
    card_id: z17.string().describe("UUID do card do cliente."),
    limite: z17.number().int().optional().describe("Quantidade de coment\xE1rios (padr\xE3o 50, m\xE1ximo 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ card_id, limite }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: card } = await supabase.from("representative_cards").select("id").eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).maybeSingle();
    if (!card) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o de acesso.");
    const take = Math.min(Math.max(limite ?? 50, 1), 200);
    const { data, error } = await supabase.from("representative_card_comments").select("id, usuario, comentario, etapa, data_comentario").eq("representative_card_id", card_id).order("data_comentario", { ascending: false }).limit(take);
    if (error) return fail(error.message);
    return ok({ total: data?.length ?? 0, comentarios: data ?? [] });
  }
});

// src/lib/mcp/tools/criar-tarefa-cliente-cross.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z18 } from "npm:zod@^3.25.76";
var criar_tarefa_cliente_cross_default = defineTool21({
  name: "criar_tarefa_cliente_cross",
  title: "Criar tarefa no cliente Onb Clientes Cross",
  description: "Cria uma tarefa vinculada a um card do painel Onb Clientes Cross, com prazo e respons\xE1vel.",
  inputSchema: {
    card_id: z18.string().describe("UUID do card do cliente."),
    titulo: z18.string().describe("T\xEDtulo da tarefa."),
    due_at: z18.string().describe("Prazo em ISO 8601, ex.: 2026-08-20T14:00:00Z."),
    assigned_to: z18.string().optional().describe("UUID do respons\xE1vel (padr\xE3o: usu\xE1rio autenticado).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ card_id, titulo, due_at, assigned_to }, ctx) => {
    const userId = requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const texto = titulo.trim();
    if (!texto) return fail("Informe o t\xEDtulo da tarefa.");
    const prazo = new Date(due_at);
    if (Number.isNaN(prazo.getTime())) return fail("Prazo inv\xE1lido. Use o formato ISO 8601.");
    const { data: card, error: cardError } = await supabase.from("representative_cards").select("id").eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).maybeSingle();
    if (cardError) return fail(cardError.message);
    if (!card) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o de acesso.");
    const { data, error } = await supabase.from("representative_card_tasks").insert({
      representative_card_id: card_id,
      titulo: texto,
      due_at: prazo.toISOString(),
      assigned_to: assigned_to ?? userId,
      status: "pendente",
      created_by: userId
    }).select("id, titulo, due_at, assigned_to, status").single();
    if (error) return fail(error.message);
    return ok({ criada: true, tarefa: data });
  }
});

// src/lib/mcp/tools/listar-tarefas-cliente-cross.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z19 } from "npm:zod@^3.25.76";
var listar_tarefas_cliente_cross_default = defineTool22({
  name: "listar_tarefas_cliente_cross",
  title: "Listar tarefas do cliente Onb Clientes Cross",
  description: "Lista as tarefas de um card do painel Onb Clientes Cross, com prazo, respons\xE1vel e status.",
  inputSchema: {
    card_id: z19.string().describe("UUID do card do cliente."),
    status: z19.enum(["pendente", "concluida", "todas"]).optional().describe("Filtro de status (padr\xE3o: todas).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ card_id, status }, ctx) => {
    requireAuth(ctx);
    const supabase = supabaseForUser(ctx);
    const { data: card } = await supabase.from("representative_cards").select("id").eq("id", card_id).eq("panel_id", CROSS_PANEL_ID).maybeSingle();
    if (!card) return fail("Card n\xE3o encontrado no painel Onb Clientes Cross ou sem permiss\xE3o de acesso.");
    let query = supabase.from("representative_card_tasks").select("id, titulo, due_at, assigned_to, status, completed_at, completed_note, created_at").eq("representative_card_id", card_id).order("due_at", { ascending: true });
    if (status && status !== "todas") query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ total: data?.length ?? 0, tarefas: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "bapxuzodzgahscatvofs";
var mcp_default = defineMcp({
  name: "monnera-parceiros",
  title: "Monnera Parceiros",
  version: "0.1.0",
  instructions: 'Ferramentas do CRM Monnera Parceiros. Use listar_paineis para descobrir pain\xE9is e etapas, listar_embaixadores para obter o parceiro_id antes de criar um lead e listar_responsaveis para definir respons\xE1veis. Cards de lead vivem no painel comercial; clientes do painel Onb Clientes Cross usam as ferramentas *_cliente_cross \u2014 inclusive mover_cliente_cross_etapa (aceita o r\xF3tulo da etapa, ex.: "Aguardando Informa\xE7\xF5es") e anexar_arquivo_cliente_cross para upload de anexos em base64. Para o painel Onb Clientes Cross use listar_clientes_cross e obter_cliente_cross para localizar cards, listar_etapas_cross para descobrir stage_ids, e as ferramentas de coment\xE1rio, tarefa e anexo espec\xEDficas desse painel. Todas as a\xE7\xF5es respeitam as permiss\xF5es do usu\xE1rio autenticado.',
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    listar_paineis_default,
    listar_leads_default,
    obter_lead_default,
    listar_embaixadores_default,
    listar_responsaveis_default,
    criar_lead_default,
    atualizar_lead_default,
    mover_lead_etapa_default,
    adicionar_comentario_default,
    criar_tarefa_default,
    criar_cliente_cross_default,
    atualizar_cliente_cross_default,
    mover_cliente_cross_etapa_default,
    anexar_arquivo_cliente_cross_default,
    listar_anexos_cliente_cross_default,
    listar_clientes_cross_default,
    obter_cliente_cross_default,
    listar_etapas_cross_default,
    adicionar_comentario_cliente_cross_default,
    listar_comentarios_cliente_cross_default,
    criar_tarefa_cliente_cross_default,
    listar_tarefas_cliente_cross_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
